# Generated by Django 3.1.6 on 2021-03-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='description goes here'),
            preserve_default=False,
        ),
    ]
